### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sweet2honey** [nieheyong/starflare#1]
https://github.com/nieheyong/starflare/blob/434848b8e40d7f6bccc38b0d523223b3ea53f326/src/pages/components/TagConflic.vue#L139

Should be `Cancel`

**Comment by nieheyong** [comment]
Thanks for the feedback, it's been fixed:
https://github.com/nieheyong/starflare/commit/b4ee86f74d9696fc52bd675f437399e48bd09345
