### ISSUE TITLE
Cloudflare Pages Deploy Error

### ISSUE THREAD

**Issue by Rvn0xsy** [nieheyong/starflare#2]
![image](https://github.com/nieheyong/starflare/assets/19944759/4f4ee84c-09b4-40c9-adfb-67a918e91f29)

![image](https://github.com/nieheyong/starflare/assets/19944759/6b7abf9f-f913-4c3e-81f5-eb1eb74dc6c7)

```
14:18:50.472	(For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
14:18:51.210	➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
14:18:51.731	➤ YN0002: │ starflare@workspace:. doesn't provide webpack (pcc690), requested by sass-loader
14:18:51.731	➤ YN0002: │ svg-sprite-loader@npm:4.3.0 doesn't provide webpack (p605ee), requested by html-webpack-plugin
14:18:51.731	➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
14:18:51.734	➤ YN0000: └ Completed in 6s 228ms
14:18:51.802	➤ YN0000: ┌ Post-resolution validation
14:18:51.803	➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
14:18:51.803	➤ YN0000: └ Completed
14:18:51.803	➤ YN0000: Failed with errors in 6s 299ms
14:18:51.844	Error: Exit with error code: 1
14:18:51.845	    at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
14:18:51.845	    at Object.onceWrapper (node:events:652:26)
14:18:51.845	    at ChildProcess.emit (node:events:537:28)
14:18:51.845	    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
14:18:51.853	Failed: build command exited with code: 1
14:18:52.704	Failed: error occurred while running build command
```

是不是需要额外配置什么信息？

**Comment by nieheyong** [comment]
cloudflare 默认的 build 环境node js 版本太高，需要指定使用低版本node js. 同时还需配置其他环境变量：

```text
CLIENT_ID  # github app client id
CLIENT_SECRET # github app client secret
NODE_VERSION 16.20.0
YARN_VERSION 1.22.19
```

<img width="1165" alt="image" src="https://github.com/nieheyong/starflare/assets/9368693/1408a50f-5b17-41f5-aa4b-8e5398a4782b">

**Comment by Rvn0xsy** [comment]
感谢解惑，部署成功后，我发现点击了登录按钮，还是会跳转到 starflare.app

在 Homepage URL 和 Authorization callback URL 我填写的都是我的自定义域名。

[https://gitstar.payloads.online/](https://gitstar.payloads.online/)

![image](https://github.com/nieheyong/starflare/assets/19944759/80901cd5-0c85-407d-9dd1-5b785368e225)

**Comment by MushR00m** [comment]
项目的.env clientid改下就好了

**Comment by nieheyong** [comment]
- 你要改下 .env 文件 https://github.com/nieheyong/starflare/blob/main/.env
- callback url 也需要更新一下，参照我的：
<img width="583" alt="image" src="https://github.com/nieheyong/starflare/assets/9368693/cb12bdfd-d3a3-42af-b3fe-cb8e2f5d222f">

**Comment by Rvn0xsy** [comment]
可以了，Callback URL需要增加 `/#/login`，感谢解惑！
