### ISSUE TITLE
目前标签数据储存在本地，如何实现永久化储存和多端同步呢

### ISSUE THREAD

**Issue by Liu8Can** [nieheyong/starflare#5]
本地化储存易因误操作导致数据丢失，除了手动导出，还有什么支持的同步方案呢
C:\Users\DanielSong\AppData\Local\Microsoft\Edge\User Data\Default\IndexedDB
https_starflare.app_0.indexeddb.blob
https_starflare.app_0.indexeddb.leveldb

**Comment by Liu8Can** [comment]
本项目未选择开源协议，我看您的所有仓库都没有开源协议，建议选择一个。

只想要保留署名权就用 MIT
涉及专利保护就用 Apache 2.0
希望衍生作品始终保持开源就用 GPLv2/GPLv3
希望仅对库的修改保持开源的就用LGPL

**Comment by nieheyong** [comment]
> 本地化储存易因误操作导致数据丢失，除了手动导出，还有什么支持的同步方案呢 C:\Users\DanielSong\AppData\Local\Microsoft\Edge\User Data\Default\IndexedDB https_starflare.app_0.indexeddb.blob https_starflare.app_0.indexeddb.leveldb

目前没有开发数据同步后端有以下原因
- 目前用户少，没动力
- 后端需要 额外收费的资源：数据库，后端服务器/worker等
- 会多一套要维护的系统，将来如果后端废弃了，整个就不能用了
- 纯前端只要一个域名费用，cloudflare page免费

**Comment by nieheyong** [comment]
> 本项目未选择开源协议，我看您的所有仓库都没有开源协议，建议选择一个。
> 
> 只想要保留署名权就用 MIT 涉及专利保护就用 Apache 2.0 希望衍生作品始终保持开源就用 GPLv2/GPLv3 希望仅对库的修改保持开源的就用LGPL

感谢建议，我稍后会选择一个开源协议

**Comment by nieheyong** [comment]
> > 本项目未选择开源协议，我看您的所有仓库都没有开源协议，建议选择一个。
> > 只想要保留署名权就用 MIT 涉及专利保护就用 Apache 2.0 希望衍生作品始终保持开源就用 GPLv2/GPLv3 希望仅对库的修改保持开源的就用LGPL
> 
> 感谢建议，我稍后会选择一个开源协议

添加了 MIT license https://github.com/nieheyong/starflare/commit/84b4183b3fb6b174239a199ed18060d99f269fbc

**Comment by Liu8Can** [comment]
> > 本地化储存易因误操作导致数据丢失，除了手动导出，还有什么支持的同步方案呢 C:\Users\DanielSong\AppData\Local\Microsoft\Edge\User Data\Default\IndexedDB https_starflare.app_0.indexeddb.blob https_starflare.app_0.indexeddb.leveldb
> 
> 目前没有开发数据同步后端有以下原因
> - 目前用户少，没动力
> - 后端需要 额外收费的资源：数据库，后端服务器/worker等
> - 会多一套要维护的系统，将来如果后端废弃了，整个就不能用了
> - 纯前端只要一个域名费用，cloudflare page免费

好的谢谢
您的项目是同类仓库中UI最漂亮的，将产品定位为更适合中国宝宝体质的星标管理工具应该不会太差的。
